<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE root [ 
	<!ELEMENT root (Course_Catalog)>
		<!ELEMENT Course_Catalog (Department+)>
		<!ELEMENT Department (Title, Chair, Course+)>
			<!ELEMENT Title (#PCDATA)>
			<!ELEMENT Chair (Professor)>
				<!ELEMENT Professor (First_Name, Middle_Initial?, Last_Name)>
					<!ELEMENT First_Name (#PCDATA)>
					<!ELEMENT Middle_Initial (#PCDATA)>
					<!ELEMENT Last_Name (#PCDATA)>
			<!ELEMENT Course (Title, Description?, Instructors, Prerequisites?)>
				<!ELEMENT Description (#PCDATA)>
				<!ELEMENT Instructors ((Lecturer, Professor*) | (Professor+, Lecturer?))>
					<!ELEMENT Lecturer (First_Name, Middle_Initial?, Last_Name)>
				<!ELEMENT Prerequisites (Prereq+)>
					<!ELEMENT Prereq (#PCDATA)>

		<!ATTLIST Course
			Number (CS106A | CS106B | CS107 | CS109 | CS124 | CS143 | CS145 | CS221 | CS228 | CS229 | EE108A | EE108B | LING180) #REQUIRED
			Enrollment (1070 | 110 | 130 | 180 | 280 | 320 | 500 | 60 | 620 | 90) #IMPLIED>
		<!ATTLIST Department Code (CS | EE | LING) #REQUIRED>
]>


<root>
	<Course_Catalog>
		<Department Code="CS">
			<Title>FMI</Title>
			<Chair>
				<Professor>
					<First_Name>Parvan</First_Name>
					<Last_Name>Parnanov</Last_Name>
				</Professor>
			</Chair>
			<Course Number="CS106A" Enrollment="180">
				<Title>SARS</Title>
				<Instructors> 
					<Lecturer>
						<First_Name> Alexander </First_Name>
						<Last_Name> Dimov </Last_Name>
					</Lecturer>
				</Instructors>
			</Course>
		</Department>
	</Course_Catalog>
</root>